"""Tests for udev rule generation, install/uninstall, and the related CLI."""

from __future__ import annotations

import os
from datetime import datetime, timezone
from pathlib import Path

import pytest
from click.testing import CliRunner

from teletop_server import devices
from teletop_server.devices import (
    DeviceRegistration,
    DeviceRegistryError,
    generate_udev_rules,
    get_device_status,
    install_udev_rules,
    register_device,
    symlink_for,
    uninstall_udev_rules,
    validate_alias,
)


# ── Fixtures ─────────────────────────────────────────────────────────────


@pytest.fixture
def isolated_data_dir(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    monkeypatch.setenv("TELETOP_DATA_DIR", str(tmp_path))
    return tmp_path


@pytest.fixture
def fake_udev_paths(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> dict[str, Path]:
    """Redirect UDEV_RULES_PATH and SYMLINK_DIR into tmp_path for safety."""
    rules = tmp_path / "etc-udev" / "99-teletop.rules"
    sym = tmp_path / "dev"
    sym.mkdir()
    monkeypatch.setattr(devices, "UDEV_RULES_PATH", rules)
    monkeypatch.setattr(devices, "SYMLINK_DIR", sym)
    # main.py imported these names at module import time — patch them too.
    from teletop_server import main as main_mod

    monkeypatch.setattr(main_mod, "UDEV_RULES_PATH", rules)
    return {"rules": rules, "symlink_dir": sym}


@pytest.fixture
def root_euid(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(os, "geteuid", lambda: 0)


@pytest.fixture
def fake_udevadm(monkeypatch: pytest.MonkeyPatch) -> list[list[str]]:
    """Capture udevadm subprocess calls without invoking the real binary."""
    calls: list[list[str]] = []

    def _fake_run(cmd: list[str], **kwargs: object) -> object:
        calls.append(cmd)

        class _Result:
            returncode = 0

        return _Result()

    monkeypatch.setattr(devices.subprocess, "run", _fake_run)
    return calls


def _reg(
    alias: str,
    *,
    serial: str | None = None,
    usb_port: str | None = None,
    vid: int | None = None,
    pid: int | None = None,
    chip: str | None = None,
) -> DeviceRegistration:
    return DeviceRegistration(
        alias=alias,
        serial_number=serial,
        usb_port=usb_port,
        vid=vid,
        pid=pid,
        chip=chip,
        created_at=datetime.now(timezone.utc),
    )


# ── Alias validation ─────────────────────────────────────────────────────


def test_validate_alias_accepts_normal_names() -> None:
    for ok in ("agv1", "AGV-2", "robot_03", "x"):
        validate_alias(ok)


def test_validate_alias_rejects_special_chars() -> None:
    for bad in ("a/b", "agv 1", "a;rm", "../etc", ""):
        with pytest.raises(DeviceRegistryError):
            validate_alias(bad)


def test_validate_alias_rejects_leading_dash() -> None:
    """A leading '-' would make /dev/esp32--foo a flag-like path."""
    with pytest.raises(DeviceRegistryError):
        validate_alias("-bad")


def test_register_device_rejects_invalid_alias(isolated_data_dir: Path) -> None:
    with pytest.raises(DeviceRegistryError):
        register_device("a/b", usb_port="3-1", vid=0x1A86, pid=0x7523)


# ── generate_udev_rules ──────────────────────────────────────────────────


def test_rules_empty_registry_has_just_header() -> None:
    out = generate_udev_rules({})
    assert "Generated by teletop-server" in out
    assert "registry empty" in out


def test_rules_serial_based() -> None:
    reg = _reg("agv2", serial="A1B2", vid=0x10C4, pid=0xEA60, chip="CP2102")
    out = generate_udev_rules({"agv2": reg})
    assert 'ATTRS{serial}=="A1B2"' in out
    assert 'ATTRS{idVendor}=="10c4"' in out
    assert 'ATTRS{idProduct}=="ea60"' in out
    assert 'SYMLINK+="esp32-agv2"' in out
    assert 'ENV{TELETOP_ALIAS}="agv2"' in out
    # Serial-pinned rule must NOT include KERNELS — that would over-constrain.
    assert "KERNELS==" not in out


def test_rules_port_based() -> None:
    reg = _reg("agv1", usb_port="3-1", vid=0x1A86, pid=0x7523, chip="CH340")
    out = generate_udev_rules({"agv1": reg})
    assert 'KERNELS=="3-1"' in out
    assert "ATTRS{serial}" not in out
    assert 'SYMLINK+="esp32-agv1"' in out


def test_rules_skip_when_vid_pid_missing() -> None:
    reg = _reg("ghost", usb_port="3-1")
    out = generate_udev_rules({"ghost": reg})
    assert "skipped ghost" in out
    assert "missing VID/PID" in out
    assert 'SYMLINK+="esp32-ghost"' not in out


def test_rules_lowercase_hex() -> None:
    """udev string matching is case-sensitive; sysfs idVendor is lowercase."""
    reg = _reg("a", serial="X", vid=0x1A86, pid=0x7523)
    out = generate_udev_rules({"a": reg})
    assert "1a86" in out and "7523" in out
    assert "1A86" not in out and "7523" in out


def test_rules_mixed_registry_sorted_by_alias() -> None:
    a = _reg("zzz", serial="Z", vid=0x10C4, pid=0xEA60)
    b = _reg("aaa", usb_port="3-1", vid=0x1A86, pid=0x7523)
    out = generate_udev_rules({"zzz": a, "aaa": b})
    assert out.index("aaa") < out.index("zzz")


# ── install / uninstall ──────────────────────────────────────────────────


def test_install_requires_root(fake_udev_paths) -> None:  # type: ignore[no-untyped-def]
    # Default geteuid on test runner is non-zero (the developer's UID).
    with pytest.raises(PermissionError):
        install_udev_rules(content="# noop\n")


def test_install_writes_rules_and_calls_udevadm(
    fake_udev_paths,  # type: ignore[no-untyped-def]
    root_euid,  # type: ignore[no-untyped-def]
    fake_udevadm,  # type: ignore[no-untyped-def]
) -> None:
    rules_path = fake_udev_paths["rules"]
    install_udev_rules(content="# hi\n")
    assert rules_path.exists()
    assert rules_path.read_text() == "# hi\n"
    assert fake_udevadm == [
        ["udevadm", "control", "--reload"],
        ["udevadm", "trigger"],
    ]


def test_install_is_atomic(
    fake_udev_paths,  # type: ignore[no-untyped-def]
    root_euid,  # type: ignore[no-untyped-def]
    fake_udevadm,  # type: ignore[no-untyped-def]
) -> None:
    rules_path = fake_udev_paths["rules"]
    install_udev_rules(content="first\n")
    install_udev_rules(content="second\n")
    # No leftover .tmp file from the second pass.
    assert not rules_path.with_suffix(rules_path.suffix + ".tmp").exists()
    assert rules_path.read_text() == "second\n"


def test_uninstall_removes_file(
    fake_udev_paths,  # type: ignore[no-untyped-def]
    root_euid,  # type: ignore[no-untyped-def]
    fake_udevadm,  # type: ignore[no-untyped-def]
) -> None:
    rules_path = fake_udev_paths["rules"]
    rules_path.parent.mkdir(parents=True, exist_ok=True)
    rules_path.write_text("# stub\n")
    assert uninstall_udev_rules() is True
    assert not rules_path.exists()
    assert fake_udevadm == [
        ["udevadm", "control", "--reload"],
        ["udevadm", "trigger"],
    ]


def test_uninstall_missing_returns_false(
    fake_udev_paths,  # type: ignore[no-untyped-def]
    root_euid,  # type: ignore[no-untyped-def]
    fake_udevadm,  # type: ignore[no-untyped-def]
) -> None:
    assert uninstall_udev_rules() is False
    # No reload should be triggered if there was nothing to remove.
    assert fake_udevadm == []


def test_uninstall_requires_root(fake_udev_paths) -> None:  # type: ignore[no-untyped-def]
    with pytest.raises(PermissionError):
        uninstall_udev_rules()


# ── Symlink probe in get_device_status ───────────────────────────────────


def test_status_populates_udev_symlink_when_present(
    isolated_data_dir: Path, fake_udev_paths  # type: ignore[no-untyped-def]
) -> None:
    register_device("agv1", usb_port="3-1", vid=0x1A86, pid=0x7523)
    sym_dir = fake_udev_paths["symlink_dir"]
    # Create a dangling symlink — get_device_status should still surface it.
    target = sym_dir / "ttyUSBX"
    link = sym_dir / "esp32-agv1"
    link.symlink_to(target)

    statuses = get_device_status(ports=[])
    assert len(statuses) == 1
    assert statuses[0].udev_symlink == str(symlink_for("agv1"))


def test_status_leaves_udev_symlink_none_when_absent(
    isolated_data_dir: Path, fake_udev_paths  # type: ignore[no-untyped-def]
) -> None:
    register_device("agv1", usb_port="3-1", vid=0x1A86, pid=0x7523)
    statuses = get_device_status(ports=[])
    assert statuses[0].udev_symlink is None


# ── CLI commands ─────────────────────────────────────────────────────────


def test_cli_udev_rules_renders(isolated_data_dir: Path) -> None:
    register_device("agv1", usb_port="3-1", vid=0x1A86, pid=0x7523)
    from teletop_server.main import cli

    runner = CliRunner()
    result = runner.invoke(cli, ["udev-rules"])
    assert result.exit_code == 0, result.output
    assert "esp32-agv1" in result.output
    assert 'KERNELS=="3-1"' in result.output


def test_cli_udev_install_without_root(
    isolated_data_dir: Path, fake_udev_paths  # type: ignore[no-untyped-def]
) -> None:
    register_device("agv1", usb_port="3-1", vid=0x1A86, pid=0x7523)
    from teletop_server.main import cli

    runner = CliRunner()
    result = runner.invoke(cli, ["udev-install"])
    assert result.exit_code == 1
    assert "requires root" in result.output


def test_cli_udev_install_as_root(
    isolated_data_dir: Path,
    fake_udev_paths,  # type: ignore[no-untyped-def]
    root_euid,  # type: ignore[no-untyped-def]
    fake_udevadm,  # type: ignore[no-untyped-def]
) -> None:
    register_device("agv1", usb_port="3-1", vid=0x1A86, pid=0x7523)
    from teletop_server.main import cli

    runner = CliRunner()
    result = runner.invoke(cli, ["udev-install"])
    assert result.exit_code == 0, result.output
    rules = fake_udev_paths["rules"]
    assert rules.exists()
    assert "esp32-agv1" in rules.read_text()
    assert ["udevadm", "control", "--reload"] in fake_udevadm


def test_cli_udev_uninstall_yes(
    isolated_data_dir: Path,
    fake_udev_paths,  # type: ignore[no-untyped-def]
    root_euid,  # type: ignore[no-untyped-def]
    fake_udevadm,  # type: ignore[no-untyped-def]
) -> None:
    rules = fake_udev_paths["rules"]
    rules.parent.mkdir(parents=True, exist_ok=True)
    rules.write_text("# stub\n")

    from teletop_server.main import cli

    runner = CliRunner()
    result = runner.invoke(cli, ["udev-uninstall", "-y"])
    assert result.exit_code == 0, result.output
    assert not rules.exists()


# ── resolve_data_dir (sudo HOME=/root regression) ────────────────────────


def test_resolve_data_dir_uses_sudo_user_home(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """When run via sudo without TELETOP_DATA_DIR, look in SUDO_USER's home."""
    fake_home = tmp_path / "talat"
    fake_home.mkdir()
    monkeypatch.delenv("TELETOP_DATA_DIR", raising=False)
    monkeypatch.setattr(os, "geteuid", lambda: 0)
    monkeypatch.setenv("SUDO_USER", "talat")

    import pwd

    class _FakePw:
        pw_dir = str(fake_home)

    monkeypatch.setattr(
        pwd, "getpwnam", lambda name: _FakePw() if name == "talat" else (_ for _ in ()).throw(KeyError(name))
    )
    from teletop_server.config import Settings
    from teletop_server.main import resolve_data_dir

    assert resolve_data_dir(Settings()) == fake_home / "teletop"


def test_resolve_data_dir_respects_explicit_env(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """An explicit TELETOP_DATA_DIR override beats the sudo fallback."""
    monkeypatch.setenv("TELETOP_DATA_DIR", str(tmp_path))
    monkeypatch.setattr(os, "geteuid", lambda: 0)
    monkeypatch.setenv("SUDO_USER", "talat")
    from teletop_server.config import Settings
    from teletop_server.main import resolve_data_dir

    # Settings reads the env var; resolve_data_dir must keep it.
    assert resolve_data_dir(Settings()) == tmp_path


def test_resolve_data_dir_normal_user_unchanged(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """SUDO_USER set without EUID=0 is a stale env crumb — ignore it."""
    monkeypatch.delenv("TELETOP_DATA_DIR", raising=False)
    monkeypatch.setattr(os, "geteuid", lambda: 1000)
    monkeypatch.setenv("SUDO_USER", "talat")
    from teletop_server.config import Settings
    from teletop_server.main import resolve_data_dir

    settings = Settings()
    assert resolve_data_dir(settings) == settings.data_dir


def test_resolve_data_dir_handles_unknown_sudo_user(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """If pwd.getpwnam can't find SUDO_USER, fall back gracefully."""
    monkeypatch.delenv("TELETOP_DATA_DIR", raising=False)
    monkeypatch.setattr(os, "geteuid", lambda: 0)
    monkeypatch.setenv("SUDO_USER", "ghost")

    import pwd

    monkeypatch.setattr(
        pwd, "getpwnam", lambda name: (_ for _ in ()).throw(KeyError(name))
    )
    from teletop_server.config import Settings
    from teletop_server.main import resolve_data_dir

    settings = Settings()
    assert resolve_data_dir(settings) == settings.data_dir


def test_udev_install_under_sudo_finds_registry_in_user_home(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
    fake_udev_paths,  # type: ignore[no-untyped-def]
    fake_udevadm,  # type: ignore[no-untyped-def]
) -> None:
    """End-to-end: udev-install reads registry from SUDO_USER's home, not /root."""
    # 1. Pre-populate the registry where the human user keeps it.
    fake_home = tmp_path / "talat"
    talat_data = fake_home / "teletop"
    talat_data.mkdir(parents=True)
    monkeypatch.setenv("TELETOP_DATA_DIR", str(talat_data))
    register_device("agv1", usb_port="3-1", vid=0x1A86, pid=0x7523)

    # 2. Drop the explicit override (sudo strips most of the user's env).
    monkeypatch.delenv("TELETOP_DATA_DIR")

    # 3. Pretend we're running as root with SUDO_USER pointing at talat.
    monkeypatch.setattr(os, "geteuid", lambda: 0)
    monkeypatch.setenv("SUDO_USER", "talat")
    import pwd

    class _FakePw:
        pw_dir = str(fake_home)

    monkeypatch.setattr(pwd, "getpwnam", lambda _: _FakePw())

    from teletop_server.main import cli

    runner = CliRunner()
    result = runner.invoke(cli, ["udev-install"])
    assert result.exit_code == 0, result.output

    rules_text = fake_udev_paths["rules"].read_text()
    assert "esp32-agv1" in rules_text
    assert 'KERNELS=="3-1"' in rules_text


def test_apply_data_dir_resolution_restores_env(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """The teardown returned by _apply_data_dir_resolution must un-set the override."""
    fake_home = tmp_path / "talat"
    fake_home.mkdir()
    monkeypatch.delenv("TELETOP_DATA_DIR", raising=False)
    monkeypatch.setattr(os, "geteuid", lambda: 0)
    monkeypatch.setenv("SUDO_USER", "talat")
    import pwd

    class _FakePw:
        pw_dir = str(fake_home)

    monkeypatch.setattr(pwd, "getpwnam", lambda _: _FakePw())

    from teletop_server.main import _apply_data_dir_resolution

    assert "TELETOP_DATA_DIR" not in os.environ
    restore = _apply_data_dir_resolution()
    assert os.environ["TELETOP_DATA_DIR"] == str(fake_home / "teletop")
    restore()
    assert "TELETOP_DATA_DIR" not in os.environ


def test_cli_udev_uninstall_aborts_without_yes(
    isolated_data_dir: Path,
    fake_udev_paths,  # type: ignore[no-untyped-def]
    root_euid,  # type: ignore[no-untyped-def]
    fake_udevadm,  # type: ignore[no-untyped-def]
) -> None:
    rules = fake_udev_paths["rules"]
    rules.parent.mkdir(parents=True, exist_ok=True)
    rules.write_text("# stub\n")

    from teletop_server.main import cli

    runner = CliRunner()
    # Send 'n' on stdin to decline the confirm() prompt.
    result = runner.invoke(cli, ["udev-uninstall"], input="n\n")
    assert result.exit_code == 0
    assert "aborted" in result.output
    assert rules.exists()
